# 이 작업의 이름을 정의합니다.
name: deploy to stRdsQuery-test

# [push]. 이 워크플로는 코드를 리포지토리에 푸시할 때마다 실행됩니다.
push:   #On Push Event We need to take action
    branches:  #Now we need to specify the branch name
    - master   
jobs:
  deploy_source:
    name: build and deploy lambda
    strategy:
      matrix:
# node 버전
        node-version: [16.x]
#빌드가 시작될 때마다 Ubuntu를 새로 설치하게 됩니다. 뭔지 잘 모름
    runs-on: ubuntu-latest
    steps:

# actions/checkout@v1이 단계에서는 Github 리포지토리에서 코드를 확인합니다.
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
      - name: zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./bundle.zip ./
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ap-northeast-2
          function_name: stRdsQuery-test
          zip_file: stRdsQueryTest.zip
